PrimeiraNota = input ("Digite a primeira nota: ")
X = int (PrimeiraNota)
SegundaNota = input ("Digite a segunda nota: ")
Y = int (SegundaNota)
TerceiraNota = input ("Digite a terceira nota: ")
Z = int (TerceiraNota)
QuartaNota = input ("Digite a quarta nota: ")
A = int (QuartaNota)
Media = (X + Y + Z + A) / 4
print ("A média aritmética é", Media)
